; Script generated by Antigravity for Multi Media Toolkit
#define MyAppName "Multi Media Toolkit"
#define MyAppVersion "1.3.4"
#define MyAppPublisher "KimBS"
#define MyAppExeName "Multi Media Toolkit.exe"
#define MyIcoName "mmt.ico"

[Setup]
; AppId는 나중에 업데이트 시 식별자로 사용되므로 고정하는 것이 좋습니다.
AppId={{6D8DF5DE-0E4A-4976-ADAA-D7DC2D8227ED}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={localappdata}\{#MyAppName}
DisableDirPage=yes
DefaultGroupName={#MyAppName}
AllowNoIcons=yes
; 설치 시 관리자 권한 요구하지 않음 (UAC 안 뜸)
PrivilegesRequired=lowest
OutputDir=.\dist
OutputBaseFilename=MMT_Setup_v{#MyAppVersion}
SetupIconFile=.\mmt.ico
UninstallDisplayIcon={app}\{#MyAppExeName}
Compression=lzma
SolidCompression=yes
WizardStyle=modern
CloseApplications=force
SetupMutex=MyAppMutex
SetupLogging=yes
; 파일 속성 버전 정보 설정
VersionInfoVersion=1.3.4.0
VersionInfoTextVersion={#MyAppVersion}
; 서명은 build_and_sign.ps1 스크립트에서 자동 처리됨

[Languages]
Name: "korean"; MessagesFile: "compiler:Languages\Korean.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"

[Files]
; 빌드된 프로그램 파일들 (publish 폴더 내용물 전체)
Source: ".\bin\Release\net10.0-windows\win-x64\publish\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "changelog.txt"; DestDir: "{app}"; Flags: ignoreversion
; 아이콘 파일 포함
Source: ".\mmt.ico"; DestDir: "{app}"; Flags: ignoreversion
; 필수 도구 파일 포함 (있을 경우만 포함, 없을 경우 프로그램 실행 시 자동 다운로드됨)
Source: ".\ffmpeg.exe"; DestDir: "{app}"; Flags: ignoreversion skipifsourcedoesntexist
Source: ".\ffprobe.exe"; DestDir: "{app}"; Flags: ignoreversion skipifsourcedoesntexist
Source: ".\yt-dlp.exe"; DestDir: "{app}"; Flags: ignoreversion skipifsourcedoesntexist

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\{#MyIcoName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\{#MyIcoName}"; Tasks: desktopicon

[Code]
const
  SYNCHRONIZE = $00100000;
  LEGACY_UPDATER_EXIT_GRACE_MILLISECONDS = 5000;
  UPDATE_WAIT_MILLISECONDS = 15000;

function OpenMutex(dwDesiredAccess: LongWord; bInheritHandle: Boolean; lpName: string): THandle;
  external 'OpenMutexW@kernel32.dll stdcall';
function WaitForSingleObject(hHandle: THandle; dwMilliseconds: LongWord): LongWord;
  external 'WaitForSingleObject@kernel32.dll stdcall';
function CloseHandle(hObject: THandle): Boolean;
  external 'CloseHandle@kernel32.dll stdcall';

function IsLegacyUpdateTarget(): Boolean;
var
  InstalledExePath: string;
  InstalledVersion: Int64;
begin
  Result := False;
  InstalledExePath := ExpandConstant('{localappdata}\{#MyAppName}\{#MyAppExeName}');
  if GetPackedVersion(InstalledExePath, InstalledVersion) then begin
    Result := ComparePackedVersion(
      InstalledVersion,
      PackVersionComponents(1, 3, 4, 0)) < 0;
  end;
end;

function InitializeSetup(): Boolean;
var
  AppMutexHandle: THandle;
  TaskkillResult: Integer;
begin
  // v1.3.2 may start Setup before the app has completely exited. Apply the
  // compatibility delay whenever an existing installation is present, even
  // if the legacy updater did not pass a silent-install switch.
  if IsLegacyUpdateTarget() then begin
    Sleep(LEGACY_UPDATER_EXIT_GRACE_MILLISECONDS);

    AppMutexHandle := OpenMutex(SYNCHRONIZE, False, 'Local\MultiMediaToolkit.SingleInstance');
    if AppMutexHandle <> 0 then begin
      WaitForSingleObject(AppMutexHandle, UPDATE_WAIT_MILLISECONDS);
      CloseHandle(AppMutexHandle);
    end;

    // If a legacy build is still alive after the grace period, close only the
    // toolkit process so its executable can always be replaced.
    Exec(
      ExpandConstant('{sys}\taskkill.exe'),
      '/F /T /IM "{#MyAppExeName}"',
      '',
      SW_HIDE,
      ewWaitUntilTerminated,
      TaskkillResult);
    Sleep(1500);
  end;
  Result := True;
end;

[Run]
; Normal installation: Show checkbox to launch
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent
; Silent installation (Update): Launch automatically without prompt
Filename: "{app}\{#MyAppExeName}"; Parameters: "/updated"; Flags: nowait; Check: WizardSilent
