; Script generated by Antigravity for Multi Media Toolkit
#define MyAppName "Multi Media Toolkit"
#define MyAppVersion "1.0.4"
#define MyAppPublisher "KBS"
#define MyAppExeName "Multi Media Toolkit.exe"
#define MyIcoName "mmt.ico"

[Setup]
; AppId는 나중에 업데이트 시 식별자로 사용되므로 고정하는 것이 좋습니다.
AppId={{6D8DF5DE-0E4A-4976-ADAA-D7DC2D8227ED}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={autopf}\{#MyAppName}
DisableDirPage=no
DefaultGroupName={#MyAppName}
AllowNoIcons=yes
; 설치 시 관리자 권한 요구
PrivilegesRequired=admin
OutputDir=.\dist
OutputBaseFilename=MMT_Setup_v{#MyAppVersion}
SetupIconFile=.\mmt.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "korean"; MessagesFile: "compiler:Languages\Korean.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
; 빌드된 프로그램 파일들 (publish 폴더 내용물 전체)
; 주의: ffmpeg, yt-dlp는 앱 시작 시 자동 다운로드하므로 인스톨러에서 제외하여 용량 다이어트 (약 300MB 절약)
Source: ".\bin\Release\net10.0-windows\win-x64\publish\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; 아이콘 파일 포함
Source: ".\mmt.ico"; DestDir: "{app}"; Flags: ignoreversion

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\{#MyIcoName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\{#MyIcoName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent
