<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <AssemblyName>Multi Media Toolkit</AssemblyName>
    <RootNamespace>YoutubeDownloader</RootNamespace>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>mmt.ico</ApplicationIcon>
    <Version>1.3.6</Version>
    <AssemblyVersion>1.3.6.0</AssemblyVersion>
    <FileVersion>1.3.6.0</FileVersion>
    <Description>Multi Media Toolkit (YoutubeDownloader)</Description>
    <Product>Multi Media Toolkit</Product>
    <Authors>KimBS</Authors>
  </PropertyGroup>

<ItemGroup>
    <PackageReference Include="LibVLCSharp.WinForms" Version="3.9.6" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3800.47" />
    <PackageReference Include="VideoLAN.LibVLC.Windows" Version="3.0.23" />
    <PackageReference Include="Xabe.FFmpeg" Version="6.0.2" />
    <PackageReference Include="Xabe.FFmpeg.Downloader" Version="6.0.2" />
    <PackageReference Include="YoutubeExplode" Version="6.6.0" />
    <PackageReference Include="YoutubeExplode.Converter" Version="6.6.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="changelog.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="mmt.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    </None>
    <None Update="Assets\LoginIcons\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    </None>
    <None Update="Assets\MMT_down.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    </None>
    <None Include="yt-dlp.exe" Condition="Exists('yt-dlp.exe')">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="ffmpeg.exe" Condition="Exists('ffmpeg.exe')">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="ffprobe.exe" Condition="Exists('ffprobe.exe')">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
